blog:
  build: .
  ports:
    - "3020:3020"
    - "3021:3021"
  extra_hosts:
    - "registry:${REGISTRY_HOST}"
  restart: always
blogdev:
  build: .
  ports:
    - "3020:3020"
    - "3021:3021"
  volumes:
    - "./:/blog"
  extra_hosts:
    - "registry:${REGISTRY_HOST}"
