blog:
  build: .
  ports:
    - "3020:3020"
    - "3021:3021"
  extra_hosts:
    - "registry:${REGISTRY_HOST}"
  restart: always
test:
  build: .
  command: mkdir output
coverage:
  build: .
  command: mkdir coverage
blogdev:
  build: .
  ports:
    - "3020:3020"
    - "3021:3021"
  volumes:
    - "./:/blog/"
  extra_hosts:
    - "registry:${REGISTRY_HOST}"
